apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: disktype
      #               operator: In
      #               values:
      #                 - "ssd"
      containers:
        - name: nginx
          image: nginx:1.16.1
          imagePullPolicy: IfNotPresent
          # securityContext:
          #   allowPrivilegeEscalation: false # drop privilege escalation
          #   privileged: false # run as non-privileged container
          envFrom:
            - configMapRef:
                name: properties
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: www
              mountPath: /var/www/html
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: nginx-pvc
