apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - persistentVolumeClaim.yaml
  - service.yaml

commonAnnotations:
  rendered-by: kustomize

commonLabels:
  app: kustomized-nginx

namePrefix: kustom-

nameSuffix: -v1
