apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: http # or the deployment's port number
  selector:
    app: nginx
