apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# resources:
#   - namespace.yaml

namespace: dev

patches:
  - replicas.yaml

configMapGenerator:
  - name: properties
    envs:
      - config.properties

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - password=dev
