apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: prod

patches:
  - path: replicas.yaml

configMapGenerator:
  - name: properties
    envs:
      - config.properties

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - password=prod
